SECRET_KEY = ''

TWILIO_ACCOUNT_SID = ""
TWILIO_AUTH_TOKEN = ""
TWILIO_SERVICE_SID = ""

MYSQL_DATABASE = ""
MYSQL_HOST = ""
MYSQL_PORT = ""
MYSQL_USER = ""
MYSQL_PWD = ""

REDIS_HOST = ""
REDIS_PORT = None
REDIS_DB = None