SECRET_KEY = ''

TWILIO_ACCOUNT_SID = ""
TWILIO_AUTH_TOKEN = ""
TWILIO_SERVICE_SID = ""

WEB_MYSQL_DATABASE = ""
WEB_MYSQL_HOST = ""
WEB_MYSQL_PORT = ""
WEB_MYSQL_USER = ""
WEB_MYSQL_PWD = ""

REDIS_HOST = ""
REDIS_PORT = None
REDIS_DB = None