# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insanic/grpc/dispatch/dispatch.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='insanic/grpc/dispatch/dispatch.proto',
    package='insanic.v1',
    syntax='proto3',
    serialized_pb=_b(
        '\n$insanic/grpc/dispatch/dispatch.proto\x12\ninsanic.v1\"B\n\x0b\x43ontextUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x18\n\x10is_authenticated\x18\x03 \x01(\x08\"]\n\x0e\x43ontextService\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0b\n\x03\x61ud\x18\x02 \x01(\t\x12\x11\n\tsource_ip\x18\x03 \x01(\t\x12\x1b\n\x13\x64\x65stination_version\x18\x04 \x01(\t\"\x85\x04\n\x0eServiceRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\x0c\x12\x38\n\x07headers\x18\x05 \x03(\x0b\x32\'.insanic.v1.ServiceRequest.HeadersEntry\x12%\n\x04user\x18\x06 \x01(\x0b\x32\x17.insanic.v1.ContextUser\x12+\n\x07service\x18\x07 \x01(\x0b\x32\x1a.insanic.v1.ContextService\x12\x12\n\nrequest_id\x18\x08 \x01(\t\x12\x32\n\x04\x62ody\x18\n \x03(\x0b\x32$.insanic.v1.ServiceRequest.BodyEntry\x12\x34\n\x05\x66iles\x18\x0b \x03(\x0b\x32%.insanic.v1.ServiceRequest.FilesEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tBodyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x15\n\x08\x46ileList\x12\t\n\x01\x66\x18\x01 \x03(\x0c\x1aQ\n\nFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.insanic.v1.ServiceRequest.FileList:\x02\x38\x01\"\x9f\x01\n\x0fServiceResponse\x12\x39\n\x07headers\x18\x01 \x03(\x0b\x32(.insanic.v1.ServiceResponse.HeadersEntry\x12\x0c\n\x04\x62ody\x18\n \x01(\x0c\x12\x13\n\x0bstatus_code\x18\x0b \x01(\x05\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32T\n\x08\x44ispatch\x12H\n\x0bhandle_grpc\x12\x1a.insanic.v1.ServiceRequest\x1a\x1b.insanic.v1.ServiceResponse\"\x00\x62\x06proto3')
)

_CONTEXTUSER = _descriptor.Descriptor(
    name='ContextUser',
    full_name='insanic.v1.ContextUser',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='insanic.v1.ContextUser.id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='level', full_name='insanic.v1.ContextUser.level', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='is_authenticated', full_name='insanic.v1.ContextUser.is_authenticated', index=2,
            number=3, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=52,
    serialized_end=118,
)

_CONTEXTSERVICE = _descriptor.Descriptor(
    name='ContextService',
    full_name='insanic.v1.ContextService',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='source', full_name='insanic.v1.ContextService.source', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='aud', full_name='insanic.v1.ContextService.aud', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='source_ip', full_name='insanic.v1.ContextService.source_ip', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='destination_version', full_name='insanic.v1.ContextService.destination_version', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=120,
    serialized_end=213,
)

_SERVICEREQUEST_HEADERSENTRY = _descriptor.Descriptor(
    name='HeadersEntry',
    full_name='insanic.v1.ServiceRequest.HeadersEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='insanic.v1.ServiceRequest.HeadersEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='insanic.v1.ServiceRequest.HeadersEntry.value', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=536,
    serialized_end=582,
)

_SERVICEREQUEST_BODYENTRY = _descriptor.Descriptor(
    name='BodyEntry',
    full_name='insanic.v1.ServiceRequest.BodyEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='insanic.v1.ServiceRequest.BodyEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='insanic.v1.ServiceRequest.BodyEntry.value', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=584,
    serialized_end=627,
)

_SERVICEREQUEST_FILELIST = _descriptor.Descriptor(
    name='FileList',
    full_name='insanic.v1.ServiceRequest.FileList',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='f', full_name='insanic.v1.ServiceRequest.FileList.f', index=0,
            number=1, type=12, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=629,
    serialized_end=650,
)

_SERVICEREQUEST_FILESENTRY = _descriptor.Descriptor(
    name='FilesEntry',
    full_name='insanic.v1.ServiceRequest.FilesEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='insanic.v1.ServiceRequest.FilesEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='insanic.v1.ServiceRequest.FilesEntry.value', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=652,
    serialized_end=733,
)

_SERVICEREQUEST = _descriptor.Descriptor(
    name='ServiceRequest',
    full_name='insanic.v1.ServiceRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='method', full_name='insanic.v1.ServiceRequest.method', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='endpoint', full_name='insanic.v1.ServiceRequest.endpoint', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='headers', full_name='insanic.v1.ServiceRequest.headers', index=2,
            number=5, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='user', full_name='insanic.v1.ServiceRequest.user', index=3,
            number=6, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='service', full_name='insanic.v1.ServiceRequest.service', index=4,
            number=7, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='request_id', full_name='insanic.v1.ServiceRequest.request_id', index=5,
            number=8, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='body', full_name='insanic.v1.ServiceRequest.body', index=6,
            number=10, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='files', full_name='insanic.v1.ServiceRequest.files', index=7,
            number=11, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_SERVICEREQUEST_HEADERSENTRY, _SERVICEREQUEST_BODYENTRY, _SERVICEREQUEST_FILELIST,
                  _SERVICEREQUEST_FILESENTRY, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=216,
    serialized_end=733,
)

_SERVICERESPONSE_HEADERSENTRY = _descriptor.Descriptor(
    name='HeadersEntry',
    full_name='insanic.v1.ServiceResponse.HeadersEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='insanic.v1.ServiceResponse.HeadersEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='insanic.v1.ServiceResponse.HeadersEntry.value', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=536,
    serialized_end=582,
)

_SERVICERESPONSE = _descriptor.Descriptor(
    name='ServiceResponse',
    full_name='insanic.v1.ServiceResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='headers', full_name='insanic.v1.ServiceResponse.headers', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='body', full_name='insanic.v1.ServiceResponse.body', index=1,
            number=10, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='status_code', full_name='insanic.v1.ServiceResponse.status_code', index=2,
            number=11, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_SERVICERESPONSE_HEADERSENTRY, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=736,
    serialized_end=895,
)

_SERVICEREQUEST_HEADERSENTRY.containing_type = _SERVICEREQUEST
_SERVICEREQUEST_BODYENTRY.containing_type = _SERVICEREQUEST
_SERVICEREQUEST_FILELIST.containing_type = _SERVICEREQUEST
_SERVICEREQUEST_FILESENTRY.fields_by_name['value'].message_type = _SERVICEREQUEST_FILELIST
_SERVICEREQUEST_FILESENTRY.containing_type = _SERVICEREQUEST
_SERVICEREQUEST.fields_by_name['headers'].message_type = _SERVICEREQUEST_HEADERSENTRY
_SERVICEREQUEST.fields_by_name['user'].message_type = _CONTEXTUSER
_SERVICEREQUEST.fields_by_name['service'].message_type = _CONTEXTSERVICE
_SERVICEREQUEST.fields_by_name['body'].message_type = _SERVICEREQUEST_BODYENTRY
_SERVICEREQUEST.fields_by_name['files'].message_type = _SERVICEREQUEST_FILESENTRY
_SERVICERESPONSE_HEADERSENTRY.containing_type = _SERVICERESPONSE
_SERVICERESPONSE.fields_by_name['headers'].message_type = _SERVICERESPONSE_HEADERSENTRY
DESCRIPTOR.message_types_by_name['ContextUser'] = _CONTEXTUSER
DESCRIPTOR.message_types_by_name['ContextService'] = _CONTEXTSERVICE
DESCRIPTOR.message_types_by_name['ServiceRequest'] = _SERVICEREQUEST
DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContextUser = _reflection.GeneratedProtocolMessageType('ContextUser', (_message.Message,), dict(
    DESCRIPTOR=_CONTEXTUSER,
    __module__='insanic.grpc.dispatch.dispatch_pb2'
    # @@protoc_insertion_point(class_scope:insanic.v1.ContextUser)
))
_sym_db.RegisterMessage(ContextUser)

ContextService = _reflection.GeneratedProtocolMessageType('ContextService', (_message.Message,), dict(
    DESCRIPTOR=_CONTEXTSERVICE,
    __module__='insanic.grpc.dispatch.dispatch_pb2'
    # @@protoc_insertion_point(class_scope:insanic.v1.ContextService)
))
_sym_db.RegisterMessage(ContextService)

ServiceRequest = _reflection.GeneratedProtocolMessageType('ServiceRequest', (_message.Message,), dict(

    HeadersEntry=_reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
        DESCRIPTOR=_SERVICEREQUEST_HEADERSENTRY,
        __module__='insanic.grpc.dispatch.dispatch_pb2'
        # @@protoc_insertion_point(class_scope:insanic.v1.ServiceRequest.HeadersEntry)
    ))
    ,

    BodyEntry=_reflection.GeneratedProtocolMessageType('BodyEntry', (_message.Message,), dict(
        DESCRIPTOR=_SERVICEREQUEST_BODYENTRY,
        __module__='insanic.grpc.dispatch.dispatch_pb2'
        # @@protoc_insertion_point(class_scope:insanic.v1.ServiceRequest.BodyEntry)
    ))
    ,

    FileList=_reflection.GeneratedProtocolMessageType('FileList', (_message.Message,), dict(
        DESCRIPTOR=_SERVICEREQUEST_FILELIST,
        __module__='insanic.grpc.dispatch.dispatch_pb2'
        # @@protoc_insertion_point(class_scope:insanic.v1.ServiceRequest.FileList)
    ))
    ,

    FilesEntry=_reflection.GeneratedProtocolMessageType('FilesEntry', (_message.Message,), dict(
        DESCRIPTOR=_SERVICEREQUEST_FILESENTRY,
        __module__='insanic.grpc.dispatch.dispatch_pb2'
        # @@protoc_insertion_point(class_scope:insanic.v1.ServiceRequest.FilesEntry)
    ))
    ,
    DESCRIPTOR=_SERVICEREQUEST,
    __module__='insanic.grpc.dispatch.dispatch_pb2'
    # @@protoc_insertion_point(class_scope:insanic.v1.ServiceRequest)
))
_sym_db.RegisterMessage(ServiceRequest)
_sym_db.RegisterMessage(ServiceRequest.HeadersEntry)
_sym_db.RegisterMessage(ServiceRequest.BodyEntry)
_sym_db.RegisterMessage(ServiceRequest.FileList)
_sym_db.RegisterMessage(ServiceRequest.FilesEntry)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), dict(

    HeadersEntry=_reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
        DESCRIPTOR=_SERVICERESPONSE_HEADERSENTRY,
        __module__='insanic.grpc.dispatch.dispatch_pb2'
        # @@protoc_insertion_point(class_scope:insanic.v1.ServiceResponse.HeadersEntry)
    ))
    ,
    DESCRIPTOR=_SERVICERESPONSE,
    __module__='insanic.grpc.dispatch.dispatch_pb2'
    # @@protoc_insertion_point(class_scope:insanic.v1.ServiceResponse)
))
_sym_db.RegisterMessage(ServiceResponse)
_sym_db.RegisterMessage(ServiceResponse.HeadersEntry)

_SERVICEREQUEST_HEADERSENTRY.has_options = True
_SERVICEREQUEST_HEADERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_SERVICEREQUEST_BODYENTRY.has_options = True
_SERVICEREQUEST_BODYENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_SERVICEREQUEST_FILESENTRY.has_options = True
_SERVICEREQUEST_FILESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_SERVICERESPONSE_HEADERSENTRY.has_options = True
_SERVICERESPONSE_HEADERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_DISPATCH = _descriptor.ServiceDescriptor(
    name='Dispatch',
    full_name='insanic.v1.Dispatch',
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=897,
    serialized_end=981,
    methods=[
        _descriptor.MethodDescriptor(
            name='handle_grpc',
            full_name='insanic.v1.Dispatch.handle_grpc',
            index=0,
            containing_service=None,
            input_type=_SERVICEREQUEST,
            output_type=_SERVICERESPONSE,
            options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_DISPATCH)

DESCRIPTOR.services_by_name['Dispatch'] = _DISPATCH

# @@protoc_insertion_point(module_scope)
