# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: insanic/grpc/dispatch/dispatch.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import insanic.grpc.dispatch.dispatch_pb2


class DispatchBase(abc.ABC):

    @abc.abstractmethod
    async def handle_grpc(self, stream):
        pass

    def __mapping__(self):
        return {
            '/insanic.v1.Dispatch/handle_grpc': grpclib.const.Handler(
                self.handle_grpc,
                grpclib.const.Cardinality.UNARY_UNARY,
                insanic.grpc.dispatch.dispatch_pb2.ServiceRequest,
                insanic.grpc.dispatch.dispatch_pb2.ServiceResponse,
            ),
        }


class DispatchStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.handle_grpc = grpclib.client.UnaryUnaryMethod(
            channel,
            '/insanic.v1.Dispatch/handle_grpc',
            insanic.grpc.dispatch.dispatch_pb2.ServiceRequest,
            insanic.grpc.dispatch.dispatch_pb2.ServiceResponse,
        )
